### ISSUE TITLE
Use try and catch statement to prevent server from crashing for invalid pdf uploads.

### ISSUE THREAD

**Issue by dting** [child-first-authority-fcc-project/webapp#109]
Current the server just locks up if a pdf that is incorrectly formatted is uploaded. Our "create" function should be robust enough that it just returns an error instead of halting the server.

**Comment by pdotsani** [comment]
@dting would it work to throw a 500 if an invalid file is uploaded?

**Comment by dting** [comment]
We don't want to throw but using try catch and sending status 500 is probably what we should do if the parsing throws.

**Comment by pdotsani** [comment]
Is this issue still open? I'll work on it if so...

**Comment by dting** [comment]
I don't believe this has been touched.
