### ISSUE TITLE
Create mongodb schema to take in pdf data

### ISSUE THREAD

**Issue by pdotsani** [child-first-authority-fcc-project/webapp#11]
Schema will look something like below.

```javascript
{
Student ID (will replace _id): Number,
LastName: String,
FirstName: String,
SchoolYear: [ Number: {
    AllAbsences: Number,
    Tardy: Number,
    Present: Number,
    Enrolled:
    }]
}
```

Any suggestions comments @dting ?

**Comment by dting** [comment]
Looks like a good start. 

Haven't thought too much about this yet so I'll try to give this a closer look so i can provide so more feedback.
