### ISSUE TITLE
Change Student model to use studentId as mongo id.

### ISSUE THREAD

**Issue by dting** [child-first-authority-fcc-project/webapp#118]

**Comment by pdotsani** [comment]
@dting Quincy had some concerns about doing this in the last meeting. He mentioned the fact we might run into bugs if student ids are not unique (which I think they are). What do you think?

**Comment by dting** [comment]
I remember from a couple weeks ago some one insisted that the student Id's will be unique. It really depends on how the ids are assigned by the district.

The main benefit that using the natural id from the student as the mongo id is that we don't need to hit the db to populate the id fields for new absence records. If they are not truly unique we will run into bugs as Quincy says. This is the main reason I was opposed to this change in the first place. 

I guess lets punt this change for now until we can get some clarification. I think it depends on how long the turn over on the student ids before they start getting recycled and how often (if ever) students will be pruned from the mongo db.
