### ISSUE TITLE
Create super admin accounts on deployed site

### ISSUE THREAD

**Issue by pdotsani** [child-first-authority-fcc-project/webapp#120]
~~Create a teacher account using seed data.~~ Create super admin accounts for Amanda and Jennifer on heroku deployment.

**Comment by dting** [comment]
This is not really needed because we don't use local login's and wouldn't be able to login to that account anyways. For tests we would just create teacher accounts in the setup of the tests.

**Comment by pdotsani** [comment]
This is something they requested at the last meeting.

**Comment by dting** [comment]
In addition to not being able to use the seeded accounts (since local logins are not enabled), seed data isn't seeded on deployment. This wouldn't be useful for anything outside of local development and even then would be of very little use.

**Comment by pdotsani** [comment]
Ok. Lets do that then... I'll change the issue to reflect the change in scope. In the meantime I'll also ask for the gmails for the users so we can give them super account access.

**Comment by dting** [comment]
I have given all the people that have logged in to the test production site super admin privileges.
