### ISSUE TITLE
update absence report model to include delta

### ISSUE THREAD

**Issue by pdotsani** [child-first-authority-fcc-project/webapp#130]
@dting 
In the absence-record controller, I am thinking of adding code that will create the delta. I haven't written out the pseudocode yet but I think this might be the best approach, unless you think there is a better way to calculate the delta in the absence-record model.

**Comment by dting** [comment]
I'm guessing the delta should be calculated in the pdf-upload  controller since the previous absence report is looked up at that point. If you calculated it in the absence-record controller you would need to look up the previous absence-record again.

**Comment by pdotsani** [comment]
@dting ok makes sense. Are we calculating for each category? (i.e. absences, enrolled, presence, tardies)

**Comment by dting** [comment]
Hmm. I think you can start with just absences and tardies.
