### ISSUE TITLE
Add delete absence report feature.

### ISSUE THREAD

**Issue by dting** [child-first-authority-fcc-project/webapp#151]
Current absence reports cannot be deleted via the client. Investigate what side effect or other actions need to happen when deleting an absence report.

**Comment by pdotsani** [comment]
@dting 

I'll look into this one.

**Comment by dting** [comment]
This change is a bit complicated because we need to decide what to do if an absence record triggers an intervention. When the record is deleted should that intervention also be deleted?

**Comment by pdotsani** [comment]
This is something we can bring up tomorrow as well. Maybe we can 'archive' them by setting another element to a boolean ie `archived: true/false`, then have a feature to actually clear the absence-report and intervention like in web browser history. This might be a big task...

**Comment by pdotsani** [comment]
@dting 

How much of a priority is this issue? I was thinking of going though the site and working on UI / UX (#223)...

**Comment by dting** [comment]
This fairly high priority but is going to require some discussion. Feel free to tackle UI stuff in the meantime.

**Comment by pdotsani** [comment]
Ok sounds good. Is the primary concern down the road when old data is taking up too much space?

**Comment by pdotsani** [comment]
@dting Ok to my understanding, here is our plan of action:

- Allow sequential uploads only by restricting the upload date within the datepicker
- Provide the option to delete the most recent Absence Report

With the second item, are there still side effects in terms of undoing interventions / outreaches / actions triggered? How should we proceed in handling these?

**Comment by dting** [comment]
We want to restrict the date on the server as well and return an error if there is an invalid date. Outreaches don't need to be touched. Created students are an issue that I'm trying to figure out. Actions are a field on the interventions and deleted along with the intervention. We would need to find the interventions created by the upload and delete them.

**Comment by dting** [comment]
Resolved by #340
