### ISSUE TITLE
On load TypeError: _.keyBy is not a function

### ISSUE THREAD

**Issue by pdotsani** [child-first-authority-fcc-project/webapp#186]
Error occurs in dashboard.controller.js:156

**Comment by pdotsani** [comment]
After more investigation... error only occurs when in the branch related to pull #187. I noticed underscore is not called anywhere in this js file, but the error doesn't seem to occur on the other branches. The code for dashboard.controller.js:156 is below:

```javascript
Intervention.current().$promise.then(function(res) {
    var counts = _.keyBy(res, '_id');
    $scope.calls = (counts['Phone Call'] || {}).count || 0;
    $scope.letters = (counts['Letter Sent'] || {}).count || 0;
    $scope.home = (counts['Home Visit'] || {}).count || 0;
    $scope.sst = (counts['SST Referral'] || {}).count || 0;
    $scope.court = (counts['Court Referral'] || {}).count || 0;
  });
```

**Comment by dting** [comment]
lodash is loaded globally on the client. It needs to be @ version 4+ to have the `_.keyBy` function. Make sure packages are up to date on your machine.

**Comment by pdotsani** [comment]
@dting would I just do this by running `npm && bower install` on my local machine?

**Comment by dting** [comment]
That should work.

**Comment by pdotsani** [comment]
I'm still getting the error message in the console even after upgrading the `package.json` and running `npm install && bower install`

**Comment by dting** [comment]
I'll take a look at this issue.
