### ISSUE TITLE
href property for a tag is 0

### ISSUE THREAD

**Issue by pdotsani** [child-first-authority-fcc-project/webapp#193]
The link for the github issues repo was broken. The controller structure was listed as below before the temporary fix:

```javascript
$scope.urls = {
  'fcc' : 'http://freecodecamp.com',
  'github-issues' : 'https://github.com/child-first-authority-fcc-project/webapp/issues'
};
```

When the html loads on the app the href which is supposed to be `urls.github-issues` string converts to `0`:

```html
<a href="0" target="_blank">
```

Will make a temporary fix by replacing href property with actual url string. But it would be nice to fix this down the road.

**Comment by dting** [comment]
I'll tackle this one. 

In the html the `{{urls.github-issues}}` is being evaluated as a subtraction. I post the pull request in a few.

**Comment by pdotsani** [comment]
Sounds good. Closing pull request #195
