### ISSUE TITLE
Datepicker not showing on Heroku build

### ISSUE THREAD

**Issue by pdotsani** [child-first-authority-fcc-project/webapp#194]
As of today, the Datepicker on pdf upload is not available on Heroku Build, this is preventing users from uploading a pdf.

**Comment by pdotsani** [comment]
Just tested this on the most updated version of the repo. Seems to be working on localhost. Maybe heroku build is an oudated version?

**Comment by dting** [comment]
I'll take this one.

**Comment by pdotsani** [comment]
@dting 

Cool. Check the trello board for a snapshot.

**Comment by dting** [comment]
Since the picker is showing up now, I'm going to close this issue.
