### ISSUE TITLE
UI Testing?

### ISSUE THREAD

**Issue by pdotsani** [child-first-authority-fcc-project/webapp#199]
@dting 

Since we're near deployment, what are your thoughts on doing some UI Testing? (ie casper, selenium)

**Comment by pdotsani** [comment]
[nightwatchjs](http://nightwatchjs.org/) also another possible solution.

**Comment by dting** [comment]
Sure. If you want to look into this that would be great. Our tests in general are pretty much non existent at this point. We might want to add some unit and functional tests as well. Most of the test files are just stubs.

**Comment by pdotsani** [comment]
Sounds good. I'll add an additional issue for the unit and functional tests.
