### ISSUE TITLE
Intervention and outreach management update

### ISSUE THREAD

**Issue by dting** [child-first-authority-fcc-project/webapp#210]
We probably need a way to delete or at least mark interventions and outreaches as archived. Currently it is only possible to add them to students.

**Comment by pdotsani** [comment]
@dting 

I'll take this one...
So possibly an additional element to the intervention and outreach models consisting of a boolean value? Along with modifications to the views and controllers?

**Comment by dting** [comment]
That sounds good. Let's just do outreach for now. Since Interventions are a little tricky. We can punt that change for later.
