### ISSUE TITLE
Parsing the pdf is timing out on heroku's hard limit of 30 seconds.

### ISSUE THREAD

**Issue by dting** [child-first-authority-fcc-project/webapp#219]
We seem to be running into the hard timeout of 30 seconds for a request when parsing large pdfs.

https://devcenter.heroku.com/articles/request-timeout

I'll take a look at possible solutions.

**Comment by dting** [comment]
From the heroku logs:

```
2016-03-03T02:05:14.760331+00:00 heroku[router]: at=error code=H12 desc="Request timeout" method=POST path="/api/pdfs/" host=fcc-childfirstauthority.herokuapp.com request_id=e37e9b23-427b-4d00-89e6-4ad2738c91a0 fwd="73.189.19.247" dyno=web.1 connect=1ms service=30643ms status=503 bytes=0
```

**Comment by pdotsani** [comment]
Sounds good. Do you think it would be helpful to add some sort of UX during the pdf upload, just to let the user know that the app hasn't frozen? Is this possible?

**Comment by dting** [comment]
I've looked into this issue and it seems like this is going to be quite a bit of work. 

To investigate the problem I stripped out all the processing of the parsed pdf data and just had the server return the parsed rows. It looks like the vast majority of the time is from the just reading and parsing the pdf. Moving the calculations to the client, while still an option, does not significantly reduce the time required for the request.

This is somewhat problematic because that means we should be using workers and a task queue to run the pdf parsing in the background.

Some reading:
https://devcenter.heroku.com/articles/asynchronous-web-worker-model-using-rabbitmq-in-node
https://elements.heroku.com/addons/cloudamqp
https://github.com/OptimalBits/bull
https://github.com/taskrabbit/node-resque
https://github.com/rschmukler/agenda

This issue seems to be intermittent. I am able to upload the pdf and confirm it with fairly large files with ~2k entries with only occasional timeout failures. However, multiple people trying to upload pdfs will definitely trigger this problem. 

I'll continue looking into this.

**Comment by pdotsani** [comment]
Is this related?
