### ISSUE TITLE
Add way to remove Schools.

### ISSUE THREAD

**Issue by dting** [child-first-authority-fcc-project/webapp#232]

**Comment by pdotsani** [comment]
I'll take this one.

**Comment by pdotsani** [comment]
For this issue, what should happen to all the students associated with the deleted school? Archive / remove / something else?

**Comment by pdotsani** [comment]
@dting 

Looks like there's already a function for this? Do we just need to make it available to the admin accounts?

```javascript
$scope.deleteSchool = function(school) {
    var deleteSchoolFn = function() {
      School.remove({id: school._id}).$promise.then(function() {
        _.pull($scope.data.schools, school);
      });
    };
    Modal.confirm.delete(deleteSchoolFn)(school.name);
  };
```

**Comment by dting** [comment]
This was never linked up because of the server side problems that arise when we just delete a school. Those need to be resolved first.
