### ISSUE TITLE
Add attendance percentage to student view.

### ISSUE THREAD

**Issue by dting** [child-first-authority-fcc-project/webapp#241]

**Comment by pdotsani** [comment]
I'll take this as part of the ui updates

**Comment by pdotsani** [comment]
@dting 

This is the exports function that I've come up with, basically a dup of the chronic and atRisk querries:

```javascript
exports.student = function(req, res) {
  var id = mongoose.Types.ObjectId;
  var pipeline = currentAbsenceRecordPipeline(req.user);
  pipeline.push({
    $match: {'entries.student': id(req.params.id)}
  });
  AbsenceRecord.aggregate(pipeline, function(err, results) {
    if(err) return handleError(res, err);
    AbsenceRecord.populate(results, '-school -entries.student',
      function(err, entries) {
        if (err) return handleError(res, err);
        console.log(entries);
        // return res.status(200).json(entries);
      });
  });
};
```

For some reason, the select feature (using exclude actually) is not working. I've tried a variety of combinations within the string and still get the whole matched object. Which is fine, but I'd rather only return the needed data.
http://mongoosejs.com/docs/api.html#query_Query-populate
http://mongoosejs.com/docs/api.html#query_Query-select

Aslo I was thinking of inserting the data into the `$scope.student` var as `$scope.student.data`.

**Comment by pdotsani** [comment]
Maybe add it to this function below? Adding on to resolving the `$promise`

```javascript
$scope.student.$promise.then(function(student) {
    _.forEach(student.interventions, function(intervention) {
      // Replaces actionDates with Date objects expected by uib-datepicker.
      if (intervention.actionDate) {
        intervention.actionDate = new Date(intervention.actionDate);
      }
    });
  });
```
