### ISSUE TITLE
Data visualization misrepresents the number of absences over time.

### ISSUE THREAD

**Issue by dting** [child-first-authority-fcc-project/webapp#242]
On second thought, a line graph doesn't correctly represent the data in a meaningful way. It could be interpreted as plotting the change over time, when in reality we have distinct data points on the given dates that the reports are uploaded. 

Figure out a meaningful way to represent the data for the visualizations.

**Comment by pdotsani** [comment]
Lets discuss this when we check-in later today. I'll take the lead once we decide the best route to go.

**Comment by pdotsani** [comment]
Based on Jennifer's response, we'll be going with pie charts.

**Comment by pdotsani** [comment]
@dting 

Based on Jennifer's feedback: 
> Pie chart. % students in CFA who are ARCA and CA compared to % students NOT in CFA who are ARCA and CA (Year to Date)

It seems like we have services in place to get all the data needed for data visualization. Would it be better to just utilize the existing services, or create new queries using the `api/visualizations` endpoint?

**Comment by dting** [comment]
Probably use existing if possible. I think you might need to add/modify them.

**Comment by pdotsani** [comment]
Just noticed she's requesting data for students that are not in CFA. Do we have a metric for this?
