### ISSUE TITLE
Add visual aides during pdf upload

### ISSUE THREAD

**Issue by pdotsani** [child-first-authority-fcc-project/webapp#255]

**Comment by dting** [comment]
This should be an interesting problem. The bottleneck at this point is having to check the students against the existing data or creating object in the database. I'm interested in seeing how we can communicate the server progress to the client.

**Comment by pdotsani** [comment]
Are there ways to trigger events during certain parts of the upload process? Since most of the work is being done on the client side, maybe a simple broadcast might do the trick?

**Comment by dting** [comment]
The upload is not the bottle neck. The server processing is taking the time. One possibility is to use websockets or poll the server about the progress. The other is to put a fake progress bar or spinner. That option isn't a real indication of progress like the bar for the parsing that is on the client tho.

**Comment by pdotsani** [comment]
punting issue for now.
