### ISSUE TITLE
Provide Markdown Editing for Notes

### ISSUE THREAD

**Issue by pdotsani** [child-first-authority-fcc-project/webapp#265]
Just a thought, could help provide more descriptive notes per intervention / outreach. Definitely not a priority but a nice to have...

**Comment by dting** [comment]
That would be a nice feature. I would say that most of the users of the app won't be familiar with markdown. Let's punt this.

**Comment by dting** [comment]
I think we need to prioritize other things for now. Closing this issue unless we get a feature request for formattable notes from cfa.
