### ISSUE TITLE
Possible Bug In Highcharts?

### ISSUE THREAD

**Issue by pdotsani** [child-first-authority-fcc-project/webapp#266]
Possible bug? Hopefully just an awesome feature that I'm unaware of...

<img width="240" alt="highchart-err" src="https://cloud.githubusercontent.com/assets/5272252/13802472/8c9d981c-eaf9-11e5-80cc-43196d841611.png">

**Comment by dting** [comment]
I think you are looking at ui-grid. That isn't a bug. That means it is the second column that group/sort has priority in.
