### ISSUE TITLE
Update ui-datepicker attribute

### ISSUE THREAD

**Issue by pdotsani** [child-first-authority-fcc-project/webapp#270]
A warning: 

> uib-datepicker settings via uib-datepicker-popup attributes are deprecated and will be removed in UI Bootstrap 1.3, use datepicker-options attribute instead

**Comment by dting** [comment]
Oops. I didn't see that this issue was assigned and made a PR for it.

**Comment by pdotsani** [comment]
All good. I haven't started working on this so I'll just review your pull.
