### ISSUE TITLE
Add outreach note when you press enter

### ISSUE THREAD

**Issue by pdotsani** [child-first-authority-fcc-project/webapp#294]
Outreach notes can only be added on click. Possible solutions are embed in a form or add a directive to the input tag:

```javascript
angular.module('app')
  .directive('ngEnter', function () {
    return function (scope, element, attrs) {
      element.bind('keydown keypress', function (event) {
        if(event.which === 13) {
          scope.$apply(function (){
              scope.$eval(attrs.ngEnter);
          });
          event.preventDefault();
        }
      });
    };
  });
```

**Comment by dting** [comment]
After playing with this for a bit. I think a better compromise is allowing the user to tab to the add button and hitting enter there. Since the notes can't be deleted pressing enter and immediately adding the note seems like it might cause unwanted notes to be added.
