### ISSUE TITLE
Archived schools still being displayed in admin. Update endpoints.

### ISSUE THREAD

**Issue by dting** [child-first-authority-fcc-project/webapp#325]

**Comment by pdotsani** [comment]
I'll take this one as a pt. 2 to the previous merge #323.

So we want these schools to not be displayed altogether? Or alternatively, provide a label to indicate they are archived?

How should we treat the associated students? Currently they're being archived as well.

**Comment by dting** [comment]
We probably want to hide them from all lists and hide all associated records as well unless explicitly requested. I'm not really sure the if best way to go about this change. Maybe think about that and we can discuss our options.

Students at this point are never listed directly. There is no real difference between an active one and a not archived one so just don't do anything with them.

**Comment by pdotsani** [comment]
Ok. How about creating a 'show archived' section in the admin section that only appears if superuser archives a school. This section would show an archived school and it's students. Could either be a new route or another UI.grid.

For assigned teachers, I'm thinking of two options:
- Notify them that their assignment has been archived at login and to contact their super admin to resolve this issue.

- Allow them to sign in, but provide a visual notifier that assignment is modified (modal and/or highlighting or label in the UI.grid.

**Comment by dting** [comment]
I was thinking more along the lines of how the interventions behave when archived for the schools.

As for the teachers. Just update assignments for teachers assigned to the school being archived to nothing.

**Comment by pdotsani** [comment]
If we remove a teacher's assignment, they would still be able to access the application? Wouldn't all the charts and graphs just yield empty? Would intervention and outreach records still be accessible after a teacher's assignment is removed?

**Comment by dting** [comment]
No removing a teacher's assignment removes their access to the app. They will be redirected to the ask admin for access page.

**Comment by pdotsani** [comment]
Got it. Thanks.
