### ISSUE TITLE
UI Grid Styles

### ISSUE THREAD

**Issue by pdotsani** [child-first-authority-fcc-project/webapp#369]
Are the ui.grid styles customizable? Had a few ideas for a restyle.

**Comment by dting** [comment]
Yes but it can be a bit tricky. There are a lot of calculations that the grid does based on sizing variables that will cause problems if altered using css. Removing padding etc will also cause problems for those calculations.

**Comment by pdotsani** [comment]
I was thinking more of changes to color, background-color, border, and possibly font-family attributes, the sizing and spacing seems to be fine.

**Comment by pdotsani** [comment]
Punting this issue unless UI changes are requested by Jennifer.
