### ISSUE TITLE
Upload PDF to app functionality

### ISSUE THREAD

**Issue by pdotsani** [child-first-authority-fcc-project/webapp#38]
Upload pdf data and parse using [pdf2table](https://github.com/SamDecrock/pdf2table).

**Comment by pdotsani** [comment]
Use this as reference: [stackoverflow](http://stackoverflow.com/questions/21926719/how-do-i-upload-a-file-using-node-js)

**Comment by dting** [comment]
I edited your issue to remove the Trello link since it is a private board. Since this is a public repository lets try to avoid linking to the Trello board.

**Comment by pdotsani** [comment]
@dting 

Based on our conversation, what do you think of this api? [angular-file-upload](https://github.com/nervgh/angular-file-upload). The [demo](http://nervgh.github.io/pages/angular-file-upload/examples/simple/) seems to provide an example of exactly what we're looking for.

**Comment by dting** [comment]
We probably will upload the entire file to the app and have the server parse it. Ya, I think we'll use angular-file-upload.
