### ISSUE TITLE
Some of the scrollbars need width their width increased for better user experience.

### ISSUE THREAD

**Issue by dting** [child-first-authority-fcc-project/webapp#406]
For scrollable content that is very large and will likely require common use of the scrollbars, having the css set to scrollbars to be very thin makes them really hard to click.

Look over all the places where the scrollbars are replaced and determine if having the scrollbars is just for a visual indication that there is more content or if the user is likely going to click the bar. Increase the width of the bars that need to be clicked.

**Comment by pdotsani** [comment]
I'll take this one.

**Comment by dting** [comment]
The only one i've noticed so far is in the grid. We might also want to change it so it overflow-y: auto instead of scroll if we increase the width. The sass mixin in common.scss allows for specification on the overflow-y type so it should be an easy change.
