### ISSUE TITLE
Determine how restrictive the roles should be.

### ISSUE THREAD

**Issue by dting** [child-first-authority-fcc-project/webapp#41]
Do we need to completely segregate the students from each school? Do teachers need to be only allowed access to their own schools or is that for convenience only?

**Comment by pdotsani** [comment]
I believe teachers should have access to their own schools only. Admin should have rights to access all schools.

**Comment by dting** [comment]
I want to know if this is a privacy requirement vs a convenience thing. Not having to do another authorization check would simplify the app.

**Comment by pdotsani** [comment]
From working in schools for five years, its not a convenience. They take the privacy requirement very seriously.

**Comment by dting** [comment]
Let's ask before we do anything.

**Comment by dting** [comment]
Looking at the Trello board again, there is a point specific saying teachers can only see their own schools. Looks like your right. I'm going to close this issue and open another about setting up authorization by school assignment.
