### ISSUE TITLE
The graphs from highchart don't always draw correctly on first load. Add redraw menu item.

### ISSUE THREAD

**Issue by dting** [child-first-authority-fcc-project/webapp#419]
I've looked into this a bit and the problem only occurs occasionally. It also fixes itself if you resize the window when it does happen or load a different graph. I think the easiest fix might be to add a menu item that calls reflow.

**Comment by dting** [comment]
After some investigation, it doesn't seem like calling redraw or reflow on the graph works even after setting isDirtyBox or the series.isDirty to true. I think a better fix might be to reverse the behavior of the sidebar to being collapsed when created. I think the bug is related to the graph grabbing the size of its parent while the sidebar animation is happening.

**Comment by pdotsani** [comment]
Interesting. So possibly could you hold the generation of the graph until the sidebar has finished resizing?

**Comment by dting** [comment]
So I a change list reversing the starting state of the sidebar, but it still doesn't fix this problem. There seems to be some sizing race condition i can't pin down. I'm going to submit the PR for the sidebar and keep looking for a fix for this problem.
