### ISSUE TITLE
Add Michael, Alex, and Jennifer to the About Page.

### ISSUE THREAD

**Issue by dting** [child-first-authority-fcc-project/webapp#427]
Confirm that they want to be added and to what extent. This page is only visible by users since it is behind the authentication wall but acknowledging their contribution would be nice.

We could consider removing the authentication requirements for this page but I don't really think that's worth the effort.

**Comment by pdotsani** [comment]
> We could consider removing the authentication requirements for this page but I don't really think that's worth the effort.  

Agreed.  

- Michael's linkedin: https://www.linkedin.com/in/codenonprofit.  
- Jennifer's linkedin: https://www.linkedin.com/in/jennifer-mcdowell   
- Alex's linkedin: https://www.linkedin.com/in/alexander-feng

**Comment by dting** [comment]
After a quick discussion at the meeting, we've decided to punt this issue.
