### ISSUE TITLE
401 Error: Invalid client

### ISSUE THREAD

**Issue by pdotsani** [child-first-authority-fcc-project/webapp#441]
Error on login:

![image](https://cloud.githubusercontent.com/assets/5272252/18320493/f4e228ce-74de-11e6-8e60-57660d5515c9.png)

**Comment by dting** [comment]
This is an incomplete deployment issue. The GOOGLE_ID and GOOGLE_SECRET need to be set ad ENV variables.

**Comment by pdotsani** [comment]
Gotcha. Config vars set under cfa email act.
