### ISSUE TITLE
Add notification that pdf has been uploaded

### ISSUE THREAD

**Issue by pdotsani** [child-first-authority-fcc-project/webapp#88]

**Comment by dting** [comment]
I'm guessing we wont use a modal for this. After the user hits upload we probably want to change the page (or just the page contents) to a loading/waiting for results page where we can confirm the upload contents or notify them of errors to prevent them from double submitting/clearing the upload field.

**Comment by pdotsani** [comment]
Ok. I'm assuming this will be done in the controller? If so, should we create a new route?

**Comment by dting** [comment]
Ya prob don't need a new state

**Comment by pdotsani** [comment]
@dting Given that the post request is initiated in the html and not the controller, how do we run functions on a successful or unsuccessful upload?

**Comment by dting** [comment]
I haven't looked too closely to this but you can change it so the post is initiated by the controller.

**Comment by dting** [comment]
I think if you use one of the modules we discussed for the client for uploading files this won't be a problem.

**Comment by pdotsani** [comment]
Ok using [ng-file-upload](https://github.com/danialfarid/ng-file-upload) for this one.

**Comment by dting** [comment]
How does that compare with the alternatives.

https://github.com/nervgh/angular-file-upload ?

**Comment by pdotsani** [comment]
[ng-file-upload](https://github.com/danialfarid/ng-file-upload) seems to have better support for single file uploads...

**Comment by dting** [comment]
SGTM. Just making sure we are taking a look at our options and documenting our decisions. 

I need to be more diligent about doing this. Commenting why we choose one library over another so when we look back later we aren't confused why we made certain choices.
